default:
  experience: 1.0
  projects: 1.0
  achievements: 1.0

ai_engineer:
  experience: 1.0
  projects: 1.2
  achievements: 1.4

backend_engineer:
  experience: 1.3
  projects: 1.0
  achievements: 0.9

data_scientist:
  experience: 1.0
  projects: 1.3
  achievements: 1.1

research_engineer:
  experience: 1.0
  projects: 1.2
  achievements: 1.5